---
prowlarr:

  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: "1.7.3"

  dnsPolicy: ClusterFirst

  env:
    TZ: Europe/London
    UMASK: "002"
    PUID: "3001"
    PGID: "513"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - golf

  service:
    prowlarr:
      ports:
        https:
          port: 9696

  ingress:
    prowlarr:
      enabled: true
      ingressClass: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: "prowlarr.theclarkhome.com"
          paths:
            - path: /
              backend:
                name: prowlarr
                service:
                  port: 9696
      tls:
        - hosts:
          - "*.theclarkhome.com"

  persistence:
    config:
      enabled: true
      type: hostPath
      mountPath: /config
      hostPath: /opt/appdata/prowlarr
