---
home-assistant:

  image:
    repository: ghcr.io/home-assistant/home-assistant
    tag: "2023.8.3"

  env:
    TZ: Europe/London

  podAnnotations:
    k8s.v1.cni.cncf.io/networks:  |
        [{
          "name":"ipvlan-static",
          "ips": ["10.58.0.241"]
        }]

  ingress:
    main:
      enabled: true
      ingressClass: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: "hass.theclarkhome.com"
          paths:
            - path: /
              pathType: Prefix
              backend:
                name: home-assistant
                service:
                  port: 8123
      tls:
        - hosts:
          - "*.theclarkhome.com"

  probes:
    liveness:
      enabled: false
    startup:
      enabled: false
    readiness:
      enabled: false

  persistence:
    config:
      enabled: true
      existingClaim: "home-assistant-volume"
      retain: true
